logan merged with sophie's code
Team-Burberry/gamut pull request #17
Opened 2021-09-01 23:19 UTC by logan-qiu

2021-09-01 23:35 UTC, robin-son1 commented on pages/profile.js
> +    axios.get('/api/getUserInfo', { params: {email: "pillsbury.doughboy@gmail.com" }})
do we have email set up in context since it's currently hardcoded to doughboy?

2021-09-01 23:36 UTC, robin-son1 commented on pages/new-post.js
> -        <Confirm colorScheme="red" done={(!top || !cat ? false: true)} handleSubmit={handleSubmit} />
Why are we removing the submit button here?

2021-09-01 23:45 UTC, matt-heindel commented on pages/profile.js
> +  // }
Is this cruft?

2021-09-01 23:45 UTC, matt-heindel commented on pages/api/getTrendingPosts.js
> +    getTrendingPosts(req.query.category)
thanks for fixing this

2021-09-01 23:45 UTC, robin-son1 requested changes
just one comment about the useeffect being hardcoded to a user

2021-09-02 04:39 UTC, logan-qiu commented on pages/profile.js
> +    axios.get('/api/getUserInfo', { params: {email: "pillsbury.doughboy@gmail.com" }})
Hard-coded :/

2021-09-02 04:43 UTC, matt-heindel approved these changes

2021-09-02 04:43 UTC, matt-heindel commented on components/new-post/Confirm.jsx
> +
Is this cruft?

2021-09-02 04:43 UTC, matt-heindel commented on pages/profile.js
> +    axios.get('/api/getUserInfo', { params: {email: "pillsbury.doughboy@gmail.com" }})
thanks for getting rid of this!

2021-09-02 04:48 UTC, merged